# Generated by Django 2.1.7 on 2021-10-19 23:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20211019_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 10, 19, 20, 45, 53, 418295)),
        ),
    ]
